### PR TITLE
Ergonomics

### PR DESCRIPTION
**Pull request by rebeccacremona**
This PR continues tweaking the ergonomics of the Browserkube/KubeCaptures system.

## Helm Charts and Registries

It turns out you can push Helm charts to registries just like Docker images, which is really nice: one can keep one’s images and the chart for deploying them all in the same spot.... which I suspect be particularly nice when/if CI eventually builds and pushes those artifacts as part of a pipeline. The minor hitch addressed by this PR: the Helm chart has to be called “browserkube”, because the parent directory has that name.... and that collided with the default `main_image` image.

So, I moved the main browserkube code and Dockerfile into a “main” subdirectory, just like in KubeCaptures, and made the default image name “browserkube-main”, also like KubeCaptures.

I also made the names of the built Docker images and their base images configurable, once again, both for further flexibility and to allow the use of self-hosted repositories, which will be necessary when building in CI.

## Dev Ergonomics: namespaces

For developer convenience, I set things up so that the `browser_namespace` is created/updated/deleted by Helm, like the other resources, so that it doesn't have to be created and subsequently managed separately. 

NOTE: this is a breaking change. Existing deployments will need to have the `browsers` namespace manually deleted before using this updated chart.

## Dev Ergonomics: storage

For developer convenience, I set this up to ship with Minio storage configured out of the box. 

Users with external S3-compatible storage just need to tweak their settings (see README.md): add `enable_minio: False` to prevent Minio from being deployed on the cluster; then, customize `storage` with credentials as before. (And.... if they don't update their settings, things will still work fine, they will just have an idle, unnecessary Minio service on their cluster.)

## Downstream

This will lead to a couple necessary changes to the BrowserKube repo: matching PR forthcoming.

### CODE REVIEW

**Comment by rebeccacremona** [comment]
## But wait, there's more

### Previous omissions

Looks like I missed a bit of default config, when moving config into values.yml in https://github.com/webrecorder/browserkube/pull/1. Whoops! This PR adds them.

### Init-profile image

In investigating https://github.com/harvard-lil/witness/issues/27, we discovered that the latest version of the minio/mc image [changed which Linux it uses](https://github.com/minio/mc/commit/7ef637884cb70587e7ab0ebd0614386fc3b35675#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557)..... and it no longer comes with `tar`, which, in our current setup, is required for `init-profile` to succeed.

So, this PR additionally makes `profile_image` configurable and for now sets the default tag to `RELEASE.2020-11-25T23-04-07` instead of latest: the previous release, which does contain `tar`.

~I haven't yet managed to verify this last set of commits locally, but will pick that up in the AM.~

**Comment by rebeccacremona** [comment]
## But wait, there's even more

### Profile storage

In order to confirm that the above-mentioned pin of `profile_image` worked, I needed to get browser profiles working locally, which brought to light some issues with how profile storage was handled: the Helm chart was hard-coded to use https only, and, while it allowed you to set different `api_endpoint`s for general storage and for profile storage, it assumed you had the same secret and access keys for both endpoints.

So, I added a new mapping to config, `profile_storage`, that can be configured very similarly to the regular `storage` mapping. And, as with regular storage, I configured it to use the cluster's minio by default, so this application works out-of-the-box, and added a mention to the README, for users who want to use custom storage.

All this: built and tested locally with https://twitter.com/engineers_feed/status/1338876470144458755 and http://example.com

**Comment by rebeccacremona** [comment]
Summary of how to redeploy, if you have a deployment from a previous version of the Helm chart:
- Helm uninstall the release
- delete the `browsers` namespace from your cluster
- add `enable_minio: False` to your `config.yml`
- remove `profile_api_endpoint` from your `config.yml`, and instead, add the `profile_storage` mapping.

**Comment by ikreymer** [comment]
Thanks for making all of these improvements to the chart!!!

**Pull request merged**
